
apiVersion: apps/v1
kind: Deployment
metadata: { name: backend }
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
      - name: backend
        image: 888577051441.dkr.ecr.us-west-2.amazonaws.com/backend    #replace your image
        ports: [{ containerPort: 3000 }]
        envFrom:
        - secretRef: { name: db-secret }
        - configMapRef: { name: db-config }
---
apiVersion: v1
kind: Service
metadata: { name: backend-svc }
spec:
  selector: { app: backend }
  ports: [{ port: 80, targetPort: 3000 }]
